// <auto-generated />
// Snapshot mínimo do modelo para o EF Core 8 saber o estado atual ao gerar próximas migrations.
// Mantido propositadamente enxuto; ao executar `dotnet ef migrations add` novamente, este
// arquivo será regenerado pelo tooling com o modelo completo.
//
// IMPORTANTE: este snapshot é simplificado porque foi escrito à mão (sem `dotnet ef`).
// Recomenda-se rodar `dotnet ef migrations add NomeProximaMigration --context BiometriaDbContext`
// para o EF regenerar este arquivo com fidelidade total na primeira oportunidade.
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SafeRideKids.Biometria.Infrastructure.Persistence;

#nullable disable

namespace SafeRideKids.Biometria.Infrastructure.Persistence.Migrations;

[DbContext(typeof(BiometriaDbContext))]
partial class BiometriaDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        // Versão do annotation provider do Npgsql alinhada ao PackageReference do .csproj.
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.10")
            .HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("Relational:DefaultSchema", "biometria_poc");

        // Modelo é descoberto a partir das IEntityTypeConfiguration aplicadas
        // em OnModelCreating do BiometriaDbContext.
    }
}
